export * from './modules/musiclist'
export * from './modules/search'
export * from './modules/artist'
export { default as web } from './modules/web'
export { default as Client } from './modules/Client'

export type { default as Song } from './api/Song'
export type { default as tag } from './api/Tag'
export type { default as Artist } from './api/Artist'
export type { default as Artist_info } from './api/Artist_info'
export type { default as Color } from './api/Color'
