export * from './modules/musiclist'
export * from './modules/search'
export * from './modules/artist'
export { default as web } from './modules/web'
export { default as Client } from './modules/Client'